[package]
name = "raytrace"
version = "0.1.0"
authors = ["Mingzhen Zhuang <superfrankie621@gmail.com>"]
edition = "2021"

[dependencies]
lodepng = "3.7"
indicatif = "0.17"
rand = "0.8"
libm = "0.2"
rayon = "1.7"
