[package]
name = "raytrace"
version = "0.1.0"
authors = ["Mingzhen Zhuang <superfrankie621@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lodepng = "3.4"
indicatif = "0.16.0"
rand = "0.8.3"